/**
 * App icon picker (v1.0.6, Settings → Appearance → App icon). Android only: each icon is a launcher
 * <activity-alias> generated by plugins/with-alternate-icons.js from assets/app-icons/icons.json (the single
 * source of ids, labels and colors); the RecipeShare native module switches which alias is enabled.
 */
import { Platform, type ImageSourcePropType } from 'react-native';
import { getAppIcon, setAppIcon } from 'recipe-share';

import ICONS from '../../assets/app-icons/icons.json';

export type AppIconId = 'default' | 'orange' | 'navy' | 'cream' | 'red' | 'green';
export const DEFAULT_APP_ICON: AppIconId = 'default';

const PREVIEWS: Record<AppIconId, ImageSourcePropType> = {
  default: require('../../assets/app-icons/default/preview.png'),
  orange: require('../../assets/app-icons/orange/preview.png'),
  navy: require('../../assets/app-icons/navy/preview.png'),
  cream: require('../../assets/app-icons/cream/preview.png'),
  red: require('../../assets/app-icons/red/preview.png'),
  green: require('../../assets/app-icons/green/preview.png'),
};

export interface AppIconOption {
  id: AppIconId;
  label: string;
  background: string;
  bowl: string;
  preview: ImageSourcePropType;
}

export const APP_ICONS: AppIconOption[] = (ICONS as { id: AppIconId; label: string; background: string; bowl: string }[]).map(
  (icon) => ({ id: icon.id, label: icon.label, background: icon.background, bowl: icon.bowl, preview: PREVIEWS[icon.id] }),
);

export function isAppIconId(value: unknown): value is AppIconId {
  return typeof value === 'string' && APP_ICONS.some((i) => i.id === value);
}

/** `<package>.LauncherIcon<Suffix>` — must match plugins/with-alternate-icons.js. */
export function aliasSuffix(id: AppIconId): string {
  return `LauncherIcon${id.charAt(0).toUpperCase()}${id.slice(1)}`;
}

/** Default first (the native module treats the first suffix as the manifest default). */
const SUFFIXES = APP_ICONS.map((i) => aliasSuffix(i.id));

export function canChangeAppIcon(): boolean {
  return Platform.OS === 'android';
}

/** The launcher icon currently enabled on the device, or undefined when it can't be read (iOS, web, tests). */
export function currentAppIcon(): AppIconId | undefined {
  if (!canChangeAppIcon()) return undefined;
  try {
    const suffix = getAppIcon(SUFFIXES);
    return APP_ICONS.find((i) => aliasSuffix(i.id) === suffix)?.id;
  } catch {
    return undefined;
  }
}

/** Switch the launcher icon. Resolves once Android has the new component state. */
export async function changeAppIcon(id: AppIconId): Promise<void> {
  if (!canChangeAppIcon()) throw new Error('Changing the app icon is only available on Android.');
  await setAppIcon(aliasSuffix(id), SUFFIXES);
}
